-- MySQL Script generated by MySQL Workbench
-- Tue 14 Feb 2023 10:31:15 AM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema suggestion_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `suggestion_db` ;

-- -----------------------------------------------------
-- Schema suggestion_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `suggestion_db` DEFAULT CHARACTER SET utf8 ;
USE `suggestion_db` ;

-- -----------------------------------------------------
-- Table `suggestion_db`.`Suggestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suggestion_db`.`Suggestions` ;

CREATE TABLE IF NOT EXISTS `suggestion_db`.`Suggestions` (
  `suggestionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `suggestion` VARCHAR(500) NULL,
  PRIMARY KEY (`suggestionID`),
  UNIQUE INDEX `suggestionID_UNIQUE` (`suggestionID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Example Data `suggestion_db`.`Suggestions`
-- -----------------------------------------------------

INSERT INTO `suggestion_db`.`Suggestions` 
  (suggestion)
  VALUES
  (
    'Example suggestion 1'
  ),
  (
    'Example suggestion 2'
  ),
  (
    'Example suggestion 3'
  ),
  (
    'Example suggestion 4'
  );

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
